name: GCC-10_build_and_test
on: [push, pull_request]

jobs:
  gcc10-build-and-test:
    runs-on: ubuntu-latest
    env:
      FC: gfortran-10
      CC: gcc-10

    steps:
    
    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/bacio
        path: bacio
        ref: v2.5.0
    
    - name: build-bacio
      run: |
        cd bacio
        mkdir build & cd build
        cmake ..
        make -j2
        make install
        
    - name: checkout-w3emc
      uses: actions/checkout@v2
      with: 
        path: w3emc

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build 
        cd build
        cmake .. 
        make -j2

    - name: test-w3emc
      run: |
        cd w3emc/build
        ctest --output-on-failure
